require = require('esm')(module)
const { RE_VIDEO, RE_IMAGE, RE_YOUTUBE, RE_VIMEO } = require('../regex')

test('RE_VIDEO', () => {
  expect(RE_VIDEO.test('/video.mp4')).toBe(true)
  expect(RE_VIDEO.test('/video.ogg')).toBe(true)
  expect(RE_VIDEO.test('test/video.ogv')).toBe(true)
  expect(RE_VIDEO.test('/test/video.ogm')).toBe(true)
  expect(RE_VIDEO.test('/video.webm')).toBe(true)
  expect(RE_VIDEO.test('/video.avi')).toBe(true)
  expect(RE_VIDEO.test('http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4')).toBe(true)
  expect('http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4'.match(RE_VIDEO)[1]).toBe("BigBuckBunny.mp4")
  expect(RE_VIDEO.test('/video.mp3')).toBe(false)
  expect(RE_VIDEO.test('/video.jpg')).toBe(false)
  expect(RE_VIDEO.test('/video.jpeg')).toBe(false)
  expect(RE_VIDEO.test('/video.png')).toBe(false)
  expect(RE_VIDEO.test('/video.gif')).toBe(false)
  expect(RE_VIDEO.test('/video.svg')).toBe(false)
  expect(RE_VIDEO.test('/video.webp')).toBe(false)
})

test('RE_IMAGE', () => {
  expect(RE_IMAGE.test('/image.jpg')).toBe(true)
  expect(RE_IMAGE.test('/image.jpeg')).toBe(true)
  expect(RE_IMAGE.test('/image.png')).toBe(true)
  expect(RE_IMAGE.test('/image.gif')).toBe(true)
  expect(RE_IMAGE.test('/image.svg')).toBe(true)
  expect(RE_IMAGE.test('/image.webp')).toBe(true)
  expect(RE_IMAGE.test('/image.mp4')).toBe(false)
  expect(RE_IMAGE.test('/image.ogg')).toBe(false)
  expect(RE_IMAGE.test('/image.ogv')).toBe(false)
  expect(RE_IMAGE.test('/image.ogm')).toBe(false)
  expect(RE_IMAGE.test('/image.webm')).toBe(false)
  expect(RE_IMAGE.test('/image.avi')).toBe(false)
  expect(RE_IMAGE.test('http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/images/BigBuckBunny.jpg')).toBe(true)
  expect('http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/images/BigBuckBunny.jpg'.match(RE_IMAGE)[1]).toBe("BigBuckBunny.jpg")
})

test('RE_YOUTUBE', () => {
  expect(RE_YOUTUBE.test('https://www.youtube.com/watch?v=27mt_xpeZTw')).toBe(true)
  expect(RE_YOUTUBE.test('https://www.youtube.com/embed/27mt_xpeZTw')).toBe(true)
  expect(RE_YOUTUBE.test('https://youtu.be/27mt_xpeZTw')).toBe(true)
  expect('https://youtu.be/27mt_xpeZTw'.match(RE_YOUTUBE)[1]).toBe("27mt_xpeZTw")
  expect('https://www.youtube.com/embed/27mt_xpeZTw'.match(RE_YOUTUBE)[1]).toBe("27mt_xpeZTw")
  expect('https://www.youtube.com/watch?v=27mt_xpeZTw'.match(RE_YOUTUBE)[1]).toBe("27mt_xpeZTw")
  expect(RE_YOUTUBE.test('https://www.youtube.com/watch?v=27mt_xpeZTw&feature=youtu.be')).toBe(true)
  expect(RE_YOUTUBE.test('https://www.youtube.com/watch?v=27mt_xpeZTw&feature=youtu.be&t=123')).toBe(true)
  expect(RE_YOUTUBE.test('https://www.youtube.com/watch?v=27mt_xpeZTw&feature=youtu.be&t=123s')).toBe(true)
})

test('RE_VIMEO', () => {
  expect(RE_VIMEO.test('https://vimeo.com/45196645')).toBe(true)
  expect(RE_VIMEO.test('https://vimeo.com/channels/staffpicks/45196645')).toBe(true)
  expect(RE_VIMEO.test('https://vimeo.com/groups/shortfilms/videos/45196645')).toBe(true)
  expect(RE_VIMEO.test('https://vimeo.com/album/2222222/video/45196645')).toBe(true)
  expect(RE_VIMEO.test('https://player.vimeo.com/video/45196645')).toBe(true)
  expect('https://vimeo.com/45196645'.match(RE_VIMEO)[1]).toBe("45196645")
  expect('https://vimeo.com/channels/staffpicks/45196645'.match(RE_VIMEO)[1]).toBe("45196645")
  expect('https://vimeo.com/groups/shortfilms/videos/45196645'.match(RE_VIMEO)[1]).toBe("45196645")
  expect('https://vimeo.com/album/2222222/video/45196645'.match(RE_VIMEO)[1]).toBe("45196645")
  expect('https://player.vimeo.com/video/45196645'.match(RE_VIMEO)[1]).toBe("45196645")
})
