#!/usr/bin/env node

const { exec } = require('child_process')

function execCallback(err, stdout, stderr) {
  if (err) {
    console.error(err)
    return
  }
  console.log(stdout)
  console.log(stderr)
}

function run(cmd) {
  console.log(cmd)
  exec(cmd, execCallback)
}

run('npx jsdoc --configure jsdoc.json --verbose')
